### ISSUE TITLE
paper: draft text

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_dem_mood#10]
- [x] intro/theory
- [x] more data
- [x] better method
- [x] superior measure
- [x] models
- [x] results
- [x] conclusions

**Comment by fsolt** [comment]
For intro/theory:

https://twitter.com/Kunkakom/status/1290775638471856132?s=20

<img width="593" alt="Screen Shot 2020-08-05 at 7 26 52 AM" src="https://user-images.githubusercontent.com/6536645/89412816-50d5bf00-d6ed-11ea-8e1f-c1350db066dd.png">

Works cited:

[Nyhan et al. 2020.  Working paper.](https://preprints.apsanet.org/engage/apsa/article-details/5e8e2bc81e9caa0012076ec0)
[Graham and Svolik 2020.  _APSR_.](https://www.cambridge.org/core/journals/american-political-science-review/article/democracy-in-america-partisanship-polarization-and-the-robustness-of-support-for-democracy-in-the-united-states/C7C72745B1AD1FF9E363BBFBA9E18867)
[McCoy, Simonovits, and Littvay 2020. Working paper.](https://psyarxiv.com/vrn85/)

[Also this tweet](https://twitter.com/tboeggild/status/1290917199155212288?s=20), which references [von Sikorski, Heiss, and Matthes' (2019) _Political Psychology_](https://onlinelibrary.wiley.com/doi/full/10.1111/pops.12638) and the scandals literature.

**Comment by casstai** [comment]
@fsolt  I made mistakes when I merged dcpo_demsupport.Rmd......  I am not sure whether the present Head part is merged with your modification. Could you please have a look at it?  Sorry for the trouble.

**Comment by fsolt** [comment]
It looked like all the changes were incorporated; I double-checked carefully and recommitted at https://github.com/fsolt/dcpo_dem_mood/commit/458aac60e2c614bf79c07e5aca8d94d8ca846bba

It looks like you're making great progress!  Can I make one small stylistic suggestion?  Inserting a return after every line (with no spaces after the period) allows later changes to be more easily identified #onhere in GitHub.  Otherwise the whole paragraph gets flagged as changed when, for example, a single comma was added.

**Comment by casstai** [comment]
> Can I make one small stylistic suggestion? Inserting a return after every line (with no spaces after the period) allows later changes to be more easily identified #onhere in GitHub. Otherwise, the whole paragraph gets flagged as changed when, for example, a single comma was added.

Of course, please!! Thanks! I will reformat them! For the superior method part, I am not pretty sure that which part you and @sammo3182 want to highlight, so far I just outlined what I think most interesting.  I am checking the dataset in the model and will wrap up the more data part asap. Anyway, since it is just a draft, I just outline the main points. Then, we could discuss it more next Tuesday.

**Comment by fsolt** [comment]
Outlining the main points is an excellent plan.  You're making great progress!

**Comment by fsolt** [comment]
I really could have sworn I saw a different piece focused on latent variables as DVs, but I can't find it now.  Here's the piece I cite in dcpo_article: [Crabtree, Charles D., and Fariss, Christopher J. (2015). "Uncovering Patterns Among Latent Variables: Human Rights and _De Facto_ Judicial Independence." _Research and Politics_, 2(3):1-9.](https://journals.sagepub.com/doi/pdf/10.1177/2053168015605343).  It makes the same point we already know: repeat analyses and combine results.

**Comment by casstai** [comment]
Juhl, S. (2019). Measurement uncertainty in spatial models: A Bayesian dynamic measurement model. Political Analysis, 27(3), 302-319.
https://www-cambridge-org.proxy.lib.uiowa.edu/core/journals/political-analysis/article/measurement-uncertainty-in-spatial-models-a-bayesian-dynamic-measurement-model/BBF72E8DD7FCCB7C468A8F9295CA6888

**Comment by fsolt** [comment]
One more citation for partisanship-over-democracy: [Bartels 2020, just out in PNAS](https://www.pnas.org/content/early/2020/08/26/2007747117)

**Comment by casstai** [comment]
I've added intro, more data, superior method, uncertainty incorporation, and conclusion parts in our draft. 
For the result part, I just listed the outline. @sammo3182  please feel free to fill up it by our results.  
@fsolt, please skim through the structure, and help us reorganize the structure since I am still kind of confused about the structure. 
1. Is the replication of APSR just another case to support the importance of incorporating measurement uncertainty, which means the replication of it could be summarized in one sentence? Or is the APSR replication of the same importance as AJPS replication? 

2. The intro part is not clear even kind of messy now because I am not sure whether and when we should introduce the literature on public democratic commitment. 

3. Temporally, I put the literature on the public commitment to democracy in the result section as one potential explanation for our null results.   Since all the literature on public commitment to democracy focuses on polarization, I mentioned the polarization measures in DCPO.  I forgot whether we run the interaction term of theta and sigma, so I just run the interaction terms in point estimates. Given the big measurement uncertainty in democracy support, it is unsurprising that the sigma was not significant. However, the coefficient has a negative sign, which means the sigma could reduce the effect of democratic support on democracy. I'm not saying we should run more models, but the DCPO does **satisfy** both **theoretical** and **methodological** requirements of studying public opinion during the era of polarization.  I totally agree with @sammo3182 that please add more about sigma in your PA paper.

4. @fsolt  may I have a  suggestion on your PA manuscript?  I added two citations in our draft, which are [Solis, J. A., & Waggoner, P. D. Measuring Media Freedom: An Item Response Theory Analysis of Existing Indicators. British Journal of Political Science, 1-20](https://www-cambridge-org.proxy.lib.uiowa.edu/core/journals/british-journal-of-political-science/article/measuring-media-freedom-an-item-response-theory-analysis-of-existing-indicators/4A6D5AE5E6F4E78D0642BFF882C1FBF6), and [Gandhi, J., & Sumner, J. L. (2020). Measuring the Consolidation of Power in Nondemocracies. The Journal of Politics, 82(4), 000-000](https://www.journals.uchicago.edu/doi/full/10.1086/708683?casa_token=DV1fQJCn2KcAAAAA%3AywiWa6lVIh1SPZJHwuik2DrDaOQQiIH42AnfsQvvRhpKYp3vUzBWBr2hErYbrF5wvhRDO-W2090O). Both focus on latent variable measurement. One of them strongly suggests that scholars who will use their measures should incorporate uncertainty, the other provides codes for uncertainty incorporation although they let their users choose whether using point estimates or incorporating uncertainty.  Maybe you could suggest that users of DCPO should be cautious about uncertainty if their interests are complex concepts and indicators are just a few. 


Anyway, please feel free to do any editions.  Btw,  I haven't updated Bib, but will do it later.

**Comment by fsolt** [comment]
I just saw and wanted to note here that the Nyhan et al. piece [I mentioned above](https://github.com/fsolt/dcpo_dem_mood/issues/10#issuecomment-669176256) is [now out in JEPOP](https://www.tandfonline.com/doi/abs/10.1080/17457289.2020.1790577?journalCode=fbep20) (and with Carey as lead author, btw)

Also, thanks @Tyhcass for the uncertainty cites for the DCPO paper!

**Comment by casstai** [comment]
Just a reminder,  @fsolt  if you haven't read our draft, please hold on for a while. I am reorganizing all structures based on your and @sammo3182 's suggestions. I have been working on the new draft and hopefully, it will be done in the next  2 or 3 hours. I will inform both of you when it is ready. Thanks.

**Comment by casstai** [comment]
Thanks to @sammo3182's results,  now the complete draft is ready.  
@fsolt if you have time, please take a look at the draft in terms of the structure.  Thanks to your and @sammo3182 's suggestions, I've shortened the article by focusing on the uncertainty.   But, it might not be concise enough.  Any feedback or suggestion would be welcomed. 
So far, I added a brief explanation for the null results in the Intro, but I am still not sure whether when we need them in Intro or not. 
The most discussion on the explanations for the null results is in the Discussion part, but I am a little confused about the gap between the public support in abstract and commitment in a specific context is a method problem, or theory problem, or both.   
Please ignore the citation problems, after adjusting the structure, I would update the citation. 
Thanks！

**Comment by fsolt** [comment]
I also just saw that Wuttke (who authored the tweetstorm I screenshot and posted above) has a very recent and coauthored piece on the topic in the BJPS that I should work in when I revise (which I promise I will be doing soon): https://www.cambridge.org/core/services/aop-cambridge-core/content/view/27BFAF99039CD7B495EFED4042BB93DF/S0007123420000149a.pdf/div-class-title-have-europeans-grown-tired-of-democracy-new-evidence-from-eighteen-consolidated-democracies-1981-2018-div.pdf

See also: https://twitter.com/PippaN15/status/1314958434568155137 which cites this book
https://global.oup.com/academic/product/myth-and-reality-of-the-legitimacy-crisis-9780198793717?cc=us&lang=en&

**Comment by fsolt** [comment]
That is, this book: https://books.google.com/books?id=nEsrDwAAQBAJ

**Comment by casstai** [comment]
Just took a quick glimpse, yes, we do need this comparative piece!!

**Comment by casstai** [comment]
@fsolt @sammo3182 I revised and shortened our paper again and also updated the Bibtex file. When you have time, please take a look at the revised piece and let me know your thoughts. We probably still need to shorten some sections, such as the discussion part. Any suggestions and editions will be welcome.

**Comment by sammo3182** [comment]
Submitted version in bf4c1fb8a109d13c8504ecedb3e3ae71774aa9ca
