### ISSUE TITLE
Measurement Error in Other Variables (Especially V-Dem)

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_dem_mood#16]
R1: The measurement error of variables included in the model should be factored in. Many of these variables (democracy, corruption, economic output) cannot be directly observed and are therefore prone to measurement error. If one believes that (a) estimating the effect of one variable on another requires incorporating measurement error; and (b) control variable Z needs to be included because it likely has an effect on both X and Y, then to **accurately adjust for the effects of Z requires that X, Y and Z all have included measurement error.**

R2: Regardless, **it would be useful to show that the critique still holds with an alternative measurement-error approach, such as Treier and Jackman's (2008) method of composition.** Speaking of which, it struck me as odd that despite the MS's assertion of the "absolute necessity" of accounting for measurement error, the MS does not do so for any of the other variables in the analysis. Given that Treier and Jackman's analysis focused on uncertainty in measures of democracy, the most obvious omission is the V-DEM democracy measure itself (which, according to the V-DEM documentation, does appear to have associated uncertainty estimates).

**Comment by fsolt** [comment]
- [x] Get the errors (@Tyhcass?)
1. - [x] V-Dem democracy scores
1. - [x] corruption scores
1. - [ ] more?
- [ ] Incorporate them into the analyses that include uncertainty (@sammo3182?)

**Comment by fsolt** [comment]
See also #18; should we decide to push DCPO to a robustness check, that should of course be taken into account when re-running our analyses with the measurement uncertainty in the other variables

**Comment by casstai** [comment]
A little update,  I am still working on collecting and cleaning the posterior distributions of Vdem. I think I should be able to have it done by tonight.  
However, V-dem has not updated the posterior distributions of indices for version 10 which we used and version 11 which is the latest one.   So, I am using version 9 in order to have posterior distributions.  Once it is done,  we can run the "method of composition" directly.  

Since the v-dem posterior distribution is from 900 times draws,  we just need to adjust the draws of our latent variable from 1000 to 900.  @sammo3182    As for R codes for the method of composition, I need to modify MCMC codes first and hope to upload it tonight if I can finish the data collection. 

There are a few data issues that I will clarify later when I finish data cleaning. 

As for corruption, Vdem has posterior distribution data for corruption, but there are many missing data.  Although I extracted them, I don't think it is useful for our analysis.  I will try to check other sources.

**Comment by fsolt** [comment]
Yikes.  They don't provide standard errors for their measures?  Something we could use to (naively) generate distributions?

**Comment by casstai** [comment]
Er, check again, they do provide confidence interval extremes. ...

**Comment by casstai** [comment]
Two simple questions, Vdem has data for Germany (1987-2019) and German Democratic Republic (1987--1990), Palestine/West Bank(1987-2019) and Palestine/Gaza (2007- 2019), but our survey data has Germany and Palestinian Territories, instead. How should we deal with them? We can get mean and sd for the overlapped year but the regime variable is different. The regime variable for Palestine/West Bank is 1 and 0 for Palestine/Gaza. Or, we can just pick Germany and Palestine/West Bank...

**Comment by casstai** [comment]
1.  Double-check, in robustness check, we will run a method of composition for both Claassen's model and DCPO model, right? 

2. Regarding the corruption variable, TI provides CPI (corruption perspective index which was used in Claassen's and DCPO model) through 1995 and 2020 but se is available only for scores after 2012.  V-dem10's corruption index is more comprehensive.  So, do we still want to use CPI or turn to V-dem's corruption for uncertainty analysis?

**Comment by fsolt** [comment]
1. [See here](https://github.com/fsolt/dcpo_dem_mood/issues/18#issuecomment-824465122), which I guess we'll discuss at our next meeting
2. We want to replicate, so stick to CPI.  We can estimate standard errors for previous years by drawing on the later data:  one fairly defensible approach would be to calculate relative errors (SE as a % of CPI) for all country-years post-2012, take the biggest one in each country, impute that relative error to all previous years in that country, use the relative errors to calculate SEs (multiply by the CPI), and then generate distributions from those SEs. 

> Two simple questions
1. Germany is Germany.  That's no trouble at all: the GDR was East Germany, for which we have no data.
2. Palestine is harder, but I guess you're right that we should match it up with the West Bank, as it has close to twice the population of Gaza.  If you wanted to be really tricky, you could merge the two distributions proportionally.  I doubt that is worth the effort.  Just another thing to note.

**Comment by casstai** [comment]
Ajps control data with sd has been pushed, however, @sammo3182 you need to use R/v10_posterior.r to create a cntrl data with 900 draws since I repeatedly failed to push the final data given its size  (2G in csv and 300m in rds).  I tried to increase the buffer and only push rds, but it still cannot work. 
@fsolt I meet the annoying branch issue again.. I have " trauma“  with BRANCH！ Since the cntrl data is big, I tried to revert the last commit, and then "HEAD detached", and then checkout, blablablas. Anyway, I don't think I can survive through BRANCH until you save me.

**Comment by sammo3182** [comment]
Thank you for the work, Cassandra. But I'm still not very sure how should we do it (correctly), especially how to incorporate it with the 1000 (or 900) draws of the key explanatory variables? Any instruction? @fsolt @Tyhcass 

p.s. Regarding the csv...why do we have to save and transfer stuff in csv? @Tyhcass

**Comment by casstai** [comment]
@sammo3182 cls' control variable data with errors is pushed.  Let me see the 900 draws for theta. I will try to have it done by tonight.

**Comment by casstai** [comment]
@sammo3182 please check [62c7a47](https://github.com/fsolt/dcpo_dem_mood/blob/master/R/dcpo_ajps_apsr_uncertainty.R) for codes of creating dcpo analysis data and  [f55be66](https://github.com/fsolt/dcpo_dem_mood/blob/master/R/cls_ajps_apsr_uncertainty.R) for cls analysis data with uncertainty

**Comment by sammo3182** [comment]
Do we really want to put this plot to the main text? This is the output of the full uncertain (DV + IV) model ![image](https://user-images.githubusercontent.com/6463211/120175964-53377580-c239-11eb-8202-0eaca7d41dd1.png)

**Comment by casstai** [comment]
En,,it seems we have different results.. The following one is from the method of composition.  Dem_support is still not statistically significant but the lagged Vdem index matters which makes sense.  @sammo3182  I am not sure but  I am wondering maybe we can adjust x_scale a little bit.  Claassen used a 100-points scale for the Vdem index, but we used Vdem's original scale of 0-1.  He did mention that the effect was so tiny that he applied simulation to test the long-run effect, 30 years long.  So, maybe convert the Vdem scale as the first step? 
![result_ajps_uncertainty](https://user-images.githubusercontent.com/46602397/120209630-8572b400-c1f4-11eb-8292-23d739e4ffc1.jpg)

**Comment by casstai** [comment]
En, one simple or probably silly question about codes in lines  674-686 in dcpo_demosupport.Rmd.  @sammo3182 
`
result_pooled &lt;- bind_rows(  
mutate(result_cls$pooled[[1]], model = "Claassen 2020a"),  
mutate(result_clsUncertain$pooled[[1]], model = "Claassen w/ Uncertainty"),  
mutate(result_dcpoUncertain$pooled[[1]], model = "DCPO")) %&gt;%   
mutate(type = "Pooled")

`
Why use pooled[[1]]? Is [[1]] the mean result of coef, created by glance.plm?  I might miss this customized function of glance, so confused about this part.  Since Hu said the model run 10 hours, I haven't run it at my end. But, I will rerun it to have a better idea. Btw, I failed to install "drhutools" @sammo3182 .... version problem.

**Comment by sammo3182** [comment]
@Tyhcass No worry about the `drhutools`, it's only for the colorful plots. Free to comment it up. You can install it from my github repo, though. 

Regarding the `pulled[[`, I don't remember exactly, but the outcome was a list embedding lists. `[[` helps reach the data frame of the coefficients and so on.

**Comment by sammo3182** [comment]
> En,,it seems we have different results.. The following one is from the method of composition. Dem_support is still not statistically significant but the lagged Vdem index matters which makes sense. @sammo3182 I am not sure but I am wondering maybe we can adjust x_scale a little bit. Claassen used a 100-points scale for the Vdem index, but we used Vdem's original scale of 0-1. He did mention that the effect was so tiny that he applied simulation to test the long-run effect, 30 years long. So, maybe convert the Vdem scale as the first step?
> ![result_ajps_uncertainty](https://user-images.githubusercontent.com/46602397/120209630-8572b400-c1f4-11eb-8292-23d739e4ffc1.jpg)

It seems you only have two models here, Cassandra? How are things like with all three models presented?

**Comment by casstai** [comment]
Here is the summary for three models, cls_point, cls_full_uncertainty, and dcpo_full_uncertainty.  The x_scale looks better.  
I still have troubles in replicating codes for cls point estimates.  Stuck on the glance part. I can show the warning message when we have the meeting. So, I just directly input estimates_clsMeanAJPS.rds. 
![point_uncertainty_ajps](https://user-images.githubusercontent.com/46602397/120332246-2b392800-c2b4-11eb-8e15-4ba7882993e6.JPG)

**Comment by casstai** [comment]
> @Tyhcass No worry about the `drhutools`, it's only for the colorful plots. Free to comment it up. You can install it from my github repo, though.
> 
> Regarding the `pulled[[`, I don't remember exactly, but the outcome was a list embedding lists. `[[` helps reach the data frame of the coefficients and so on.

En, so , Pulled[[]] just picked the first data frame of coefficients to draw the graph. Since we emphasize the uncertainty, will it better to use the mean of coefficients and sd instead of randomly using one result? MOC summary used the mean of coefs.

**Comment by casstai** [comment]
@sammo3182 I have uploaded "pure_cls_ajps/apsr" and "exp_cls_ajps/apsr" into OSF storage. Please use them to replace  original "cls_ajps" and "cls_apsr" in our uncertainty estimates. 
@fsolt  so, if I am right, we decided to use our data which is exp_cls_ajps/apsr" in our comparison.  Is that right? 
So far, since we cannot fully replicate Claassen's apsr piece,   I run both pure and exp in MOC for apsr.  The results are the same with each other and with our previous replication.

**Comment by casstai** [comment]
@fsolt @sammo3182 You can also check these results in the paper. rmd. 
So, in simulation, claassen's pure data showed support(t-1) was negatively significant. When we added all uncertainty for both IVs and DV,  Dcpo's support (t-1) is negatively significant. 

Pure_claassen_apsr_with_fulluncertainty
![pure_cls_apsr](https://user-images.githubusercontent.com/46602397/122658624-250ccd80-d135-11eb-832e-c9b22f68e260.jpg)

expanded_claassen_apsr_with_fulluncertainty
![exp_cls_apsr](https://user-images.githubusercontent.com/46602397/122658627-2c33db80-d135-11eb-8c51-3cc9c08b3bf0.jpg)

**Comment by sammo3182** [comment]
Done with eeea4386873134255517d6e105c992ddcb1faea1
