### ISSUE TITLE
better measure: run validation tests on full dataset

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_dem_mood#2]
Prepare
- [x] modify R/argon/ code as needed to use data-raw/dem_mood.csv
- [x] consider argument for with_min_yrs()
- [x] edit call.txt to email yourself, etc.
- [x] make sure destination directories exist!

Then run on argon:
- [ ] Model 5 internal: internal R/argon/dcpo_demsupport/R/claassen_m5.sh
- [ ] Model 5 external: R/claassen_kfold.R (runs locally, not on argon)
- [x] DCPO internal: R/argon/dcpo_demsupport/R/processing.sh
- [x] DCPO external: R/argon/dcpo_demsup_kfold/R/processing.sh

**Comment by casstai** [comment]
@fsolt claassen_m5_2k_2020-06-07-22-00.rda is ready. However, it is big, 293M so that I cannot push it here.

**Comment by casstai** [comment]
@fsolt  why run Model 5 external: R/claassen_kfold.R locally, not on argon?  I submitted the job to argon already...I mean I can run it locally.

**Comment by fsolt** [comment]
> @fsolt claassen_m5_2k_2020-06-07-22-00.rda is ready. However, it is big, 293M so that I cannot push it here.

Yeah, that's way too big for GitHub; as you know, stanfit objects almost always are.  Okay, two things:

1. Can you please use `shinystan` to confirm that the `Rhat`s indicate convergence and there are no other problems?  
1. Also please use `rstan::extract` to get just the `theta` parameter.  How big is that object?  For @sammo3182's purposes, 100 draws are almost certainly sufficient.  If `theta` alone is still too big, cut it down to just 100 draws, and then commit *that*, please.

> @fsolt why run Model 5 external: R/claassen_kfold.R locally, not on argon? I submitted the job to argon already...I mean I can run it locally.

 Oh, it *can* run on argon, but it's not set up to take advantage of the available cores.

**Comment by Tyhcass** [comment]
@fsolt I used claassen_input_raw1 as the input, and submitted a kfold job to argon twice.  However, the jobs were aborted twice.  Actually, I also used raw input produced by adding one line comment to delete out range data two days ago. It worked well and I got kfold.rda. So, I am thinking maybe the problem is caused by countrycode since we didn't change anything else. But I didn't see any codes related to  countrycode.  I don't know where the problem is. Sigh.
