### ISSUE TITLE
Careful Revision

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_dem_mood#29]
_APSR RR2_

> I should also note that our editorial processes are such that we only conditionally accept articles once all revisions to the text and Supplemental Materials are complete, as no substantive changes are expected after that point. This is the stage at which you should carefully review the manuscript and related materials for clarity of exposition.

- [x] Wording in the manuscript
- [ ] Replication files

**Comment by Tyhcass** [comment]
@fsolt @sammo3182 For GDP data, after using the latest pen world table data, actually we only have 13 country-year GDP missing excluding 2020 data. So, I  am wondering maybe we don't need multiple imputations. Do you think it is ok to fill up the 13 missing by using IMF data or WDI data?  IMF and WDI are similar to each other, but en, kind of different from the Penn world table's data.

**Comment by sammo3182** [comment]
Btw, why world table data can have eco data that IMF or WDI don’t have? Are they reliable? @tyhcass

Sent from Mail for Windows

**Comment by sammo3182** [comment]
That amazing! As long as the ratio is less than  1% (or 10% ?) according to Gary King, the missing should not be a problem. Not saying imputing on TSCS is always a tricky move. I don’t think directly using IMF and WDI is appropriate unless we modeling the relation between IMF/WDI with world table data and imputing---again multiple imputations should be used if that is what we choose to do next. How do you think, Fred? @fsolt 

Sent from Mail for Windows

**Comment by fsolt** [comment]
> Btw, why world table data can have eco data that IMF or WDI don’t have? Are they reliable? 

They are reliable and much used.  They are an academic project, rather than an IO one, so much less bureaucracy involved.

> That amazing! As long as the ratio is less than  1% (or 10% ?) according to Gary King, the missing should not be a problem. Not saying imputing on TSCS is always a tricky move. I don’t think directly using IMF and WDI is appropriate unless we modeling the relation between IMF/WDI with world table data and imputing---again multiple imputations should be used if that is what we choose to do next. How do you think, Fred? @fsolt

I agree with Hu that one cannot plug in data from IMF or WDI without modeling; we definitely shouldn't do that.  The question is whether we (a) jump through the MI hoops for 13 country-years or (b) just rowwise delete them.  As Hu says, it would be hard to imagine that dropping that tiny fraction of observations would matter.  How many 2020 observations do we have in total?

**Comment by casstai** [comment]
Here is some update. 
In addition to [penn world table](https://www.rug.nl/ggdc/productivity/pwt/?lang=en), I also used latest [Maddison Project Database 2020](https://www.rug.nl/ggdc/historicaldevelopment/maddison/releases/maddison-project-database-2020), which employed a "similar" (just similar not the same since the estimates of GDPPC are different from these two projects) estimation approach with penn world table (built by the same project team) but with much more historical and adjusted data.  Both of them have their advantages, so I am not sure which we should choose and would love to listen to your thoughts @fsolt @sammo3182 . 

1. Maddison project and Penn tables definitely have more available data than IMF and WDI.  Generally, Maddison's data is more conservative and Pen table's one is more aggressive among 4 datasets. Note: I used the real GDP national account variable which is supposed to use for cross-country comparison if I understand correctly. 

2. Compared to Penn tables, **Maddison project has GDPPC data for former USSR countries** before the collapse of USSR. **However, Maddison project has no 2019 data and somehow UAE's data is 0 for 1991 and 1992**.  For the **correct data,** if we use Maddison project, we will have **60 missing** for Guyana and Suriname from 1988 to 2017.  For **our expanded data**, there are 236 missing (2019 data for a total of 143 countries and 93 missing cntry for  Guyana, Suriname, and Kosovo). 

3. Compared to Maddison project,  **Penn table has the latest 2019 data but no data for former USSR countries** before SU's collapse. For correct data, there are **73 missing country-year obs,** most from the former USSR countries in 1988 and 1989 + Libya for 30 years. For expanded data, **there are 109 missing county-year obs**, including former USSR in 1988 and 1989 + Libya and Kosovo for 30 years. 

4. IMF and WDI have 2019 data and data for Guyana, Suriname, and Kosovo but have more missing in total.

**Comment by sammo3182** [comment]
Fred @fsolt and Cassandra @Tyhcass,  allow me to offer an alternative view: given GDP is no more than a control and R1 challenged us about using multiple imputations. Why don’t we just use the IMF- WDI’s GDP data plus MIs in the main text and show  that this new technique does not change anything. Then, in the appendix, if we want, we can use a data rich version (I vote for world table for less missing) on the DCPO version. Or we can even save the new GDP to the data paper. How do you think? 

Sent from Mail for Windows

**Comment by casstai** [comment]
@fsolt @sammo3182  Updated correct data and expanded correct data have been uploaded!!! Finally!!!  

1. For the number of observations, I checked them at my end and now results have a consistent number of observations.  For correct data, the number of observations is 135 in both AJPS and APSR models.  For expanded data, the number of obs is 143 for all models in AJPS and basic models in APSR. The number of obs will reduce to 141 for models including Corruption index in APSR since there are two countries that do not have corruption index.  

2. I have imputed GDP and Resource dependence by using linear multiple imputations. However, as for resource dependence, the way in which we deal with missing is different from the original ways. We can add a brief footnote if it is necessary.  As a result, it might take a longer time to run all models since now we incorporate many uncertainties.  

3. However, please don't pull the repo until I push paper Rmd which should be done today. 

4. We have used up the storage on OSF. So,  just double-check, we don't need previous pure_cls_xx and exp_cls_xx files, right?  If we don't need them, I will delete them so that I can upload dcpo analysis data which probably cannot be done until later this week.

**Comment by casstai** [comment]
Ok, the manuscript is ready.  Do we need to add a "GDP and Resource Dependence" part in Replication Notes?  Since we use multiple imputations for GDP and Resource Dependence, I think @fsolt and @sammo3182 are better qualified to write up this part.  @sammo3182 would you like to have a try?

**Comment by casstai** [comment]
@fsolt, one quick question.  Our dcpo_input.rda has 144 countries whereas  dcpo_input_raw. csv. has 148 after formating. Actually, only one meaningful difference is Bahrain. Our dcpo_theta was apparently created from dcpo_input. rda.  So, my question is, are you ok with keeping using dcpo_input.rda and corresponding dcpo_theta?  @fsolt @sammo3182 
.

**Comment by fsolt** [comment]
I not sure I follow this question, Cassandra.  Are you saying we have more source data than is currently incorporated in dcpo_theta?  Is dcpo_theta not based on the same source data used in the corresponding analysis in the text?

**Comment by casstai** [comment]
Yes, we have more source data in dcpo_input_raw. The dcpo_theta is supposed to be based on the same source data. I am not sure whether I used the latest dcpo_theta. Could you please check your theta file and input data and upload them to osf?

**Comment by casstai** [comment]
@fsolt @sammo3182  Coding files for data are ready.  The files committed in [f3ff619 ](https://github.com/fsolt/dcpo_dem_mood/commit/71b25faa3799b9e04cc257878937c2c7458e52a5) were analysisData.R controlv.R and vdem_variables.R. These three should create analysis data from scratch.  All raw data has been uploaded to osf repo. I have tested them from creating data to compiling pdf at my end. I didn't see any error so far. 

However,  please try to create the data and run our models from scratch to see whether they can work well at your end.  
To do it, please first download the data with data "2021-12-14" to your data folder and then run vdem_variables.R, controlv.R and analysisData.R  in order to create analysis data.  Please let me know if you meet any problems.

**Comment by sammo3182** [comment]
Addressed in #42
