### ISSUE TITLE
Country-year crosswalks

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_dem_mood#5]
As @Tyhcass pointed out via email, there are many difficulties matching the DCPO surveys with the Claassen data.  Surveys in DCPO but not in Claassen are easy to filter out.  The parts that need attention are when Claassen assigns the wave year rather than the survey year and the surveys he uses that are not yet in DCPO:

### Known year issues
- [x] afrob: for waves 1 to 5, Claassen used wave year rather than survey year 

- [x] cses: Portugal 2004 listed as 2005 in Claassen's data

- [x] amb_combo: Brazil, Uruguay, Venezuela 2007 listed as 2006 by Claassen; Guyana 2009 as 2008

- [x] many others
**All of the above fixed in a batch in https://github.com/fsolt/dcpo_dem_mood/commit/35c0e985442b24775e7b0234fd1b86c1c748c615**

### Known missing survey issues
- [x] asianb3
- [ ] arabb4: missing South Sudan (error: there's no South Sudan survey in arabb)
- [x] amb: [there are _many_ (33) country surveys](https://github.com/fsolt/DCPOtools/issues/28#issuecomment-643516552_) that are not included in the combo dataset (I'm secretly very happy to learn this—moar data! lol)
- [x] cses Portugal 2002
- [x] cses Taiwan 2001
- [ ] lb Dominican Republic 2003 (error: DR not in 2003 or previous lb, confirmed by [lb web](http://www.latinobarometro.org/latOnline.jsp))
- [ ] lb Spain 2015 (error: Spain not in lb2015 file, and no included countries have 784/1000 on threestate. ESP never had just 1000 respondents.)
- [x] pew Russia 2005 (in pew2005_11)
- [x] wvs Sweden 1999 (in WVS wave 4, but excluded from wvs_combo.  Sigh.)
- [ ] wvs Bahrain 2014 (error: there's no WVS data on Bahrain, confirmed by [wvs web](http://www.worldvaluessurvey.org/WVSDocumentationWV6.jsp).)

**Comment by casstai** [comment]
@fsolt I checked the sample sizes in amb_countries, there are MANY differences between amb_countries and Claassen's sample size.  Also, although Claassen elaborated that sample sizes may be different from the number of respondents, his sample size is just the number of respondents most time. I am confused. It seems it is not useful to categorize non-response.

**Comment by fsolt** [comment]
I've concluded that our replication is going to be slightly imperfect.  There's no way, for example, to get lb Dominican Republic 2003 and lb Spain 2015--these surveys simply don't exist.  We just have to do our best to follow the documentation.  It says how non-responses were categorized, so that's how we'll do it.  What does it say about why "sample sizes may be different from the number of respondents"?  Because of weighting?

**Comment by casstai** [comment]
In case I misunderstand what he said, I copied his explanation on supplementary material here.   I assume in his "supdem raw survey marginals" file, the sample column refers to trial since the response column refers to the number of respondents who give their support. 
claassen, 2019, ajps.
"As described below, the latent trait measurement model takes a binomial response, which requires two pieces of information: the number of “trials” and the number of these that were “successful.” I therefore gathered two quantities for each survey question. First, the number of respondents asked each relevant survey question (this was usually, but not always, the full sample size). Second, the number of respondents providing a response that was supportive of democracy. This may include the response “democracy is preferable to any other kind of government” in the three statements question, disagreeing that the military should rule, or oﬀering a response above the median on a 0-10 scale for the question regarding the importance of democracy to the respondent. It follows that all other possible responses (i.e., the diﬀerence between the sample size and the number of supportive respondents) were treated, similarly, as not supportive of democracy. These nonsupportive respondents may have actively opposed democracy, (e.g.,“an authoritarian government can be preferable to a democratic one”), chosen an intermediate response (e.g., “for someone like me, it does not matter what kind of government we have”), responded with “don’t know,” or refused to provide any response. "

**Comment by fsolt** [comment]
Ah.  Yeah, I interpret "the number of respondents asked each relevant survey question (this was usually, but not always, the full sample size)" to refer to surveys with split samples.

**Comment by fsolt** [comment]
Do you see items in which the numbers match up if the non-responses are omitted?

**Comment by casstai** [comment]
I checked. Actually, he didn't omit any non-responses or missing values at all. Sigh...

**Comment by casstai** [comment]
> Ah. Yeah, I interpret "the number of respondents asked each relevant survey question (this was usually, but not always, the full sample size)" to refer to surveys with split samples.

I think you are right....

**Comment by fsolt** [comment]
I'm working on the two CSES missing surveys, btw.  They're (only) in the CSES combo file, which is a real problem to deal with, which is why I went with the single wave files in the first place.  Sigh.

**Comment by fsolt** [comment]
Closed by https://github.com/fsolt/dcpo_dem_mood/commit/e65cdf1c938129a3c76dfcd372a2dc0a951e69ba
