### ISSUE TITLE
analysis: update control variable dataset

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_dem_mood#7]
needs to incorporate all country-years in [dcpo_input_cy.rda](https://github.com/fsolt/dcpo_dem_mood/blob/master/data/dcpo_input_cy.rda)

**Comment by casstai** [comment]
I've been working on control variables. Sorry for falling behind schedule.

**Comment by casstai** [comment]
@fsolt @sammo3182  I just update cntrl_data_imp,vdem_na, and imf_wdi_pen in data.  There are some problems I don't know how to address. 
1.  Vdem_na list country names which don't have information in Vdem due to different reasons. One of reasons is the new built countries. For example, in our dcpo_input_yc, we have Slovakia	1990, 1992, however, Slovakia probably still belonged to Czech in 1990 and 1992 in Vdem. There are also many of these similar problems. I don't know how to deal with them systematically.  One simple problem is Taiwan, which is in our data, but no population information from WB and Penn table. If we save it in our data, then we just need to fill up the population information.   Belize, we have it in our data, but Vdem doesn't include it since it is a small country.

2. For imputed  GDP_percapita.  In cntrl_data_imp, I tried to impute missing IMF gdp_percapita by linear imputation on WDI and Pen world table, but there are still many missing values. I am not sure whether I did it right, so I attached imf_wdi_penn file which includes GDP from IMF, Worldbank WDI and Penn world table 9.1.   

3.  Actually, now  cntrl_data_imp includes control variables for all 142 countries in our data between 1987 and 2019(1987 is included because we need lagged data).  Since we need to run the whole data with our theta from 1988 through 2019 finally , so I include all country_year variables instead of only variables in country_year which we have public opinion data.    But, I still save a version for country_year in our dcpo_input if it is needed.

**Comment by sammo3182** [comment]
A couple of comments for the discussion: 
> 
> 1. Vdem_na list country names which don't have information in Vdem due to different reasons. One of reasons is the new built countries. For example, in our dcpo_input_yc, we have Slovakia	1990, 1992, however, Slovakia probably still belonged to Czech in 1990 and 1992 in Vdem. There are also many of these similar problems. I don't know how to deal with them systematically.  One simple problem is Taiwan, which is in our data, but no population information from WB and Penn table. If we save it in our data, then we just need to fill up the population information.   Belize, we have it in our data, but Vdem doesn't include it since it is a small country.

As long as the missing does not attribute to a deterministic or systematic reason, I suggest to ignore them for now and leave a footnote about it. Our purpose is to conduct a proper comparison, but if there's nothing comparable (such as there was no Slovakia until 1993, and Taiwan is a province of PRC as the WB suggests), that's out of the scale of the paper. 

> 2. For imputed  GDP_percapita.  In cntrl_data_imp, I tried to impute missing IMF gdp_percapita by linear imputation on WDI and Pen world table, but there are still many missing values. I am not sure whether I did it right, so I attached imf_wdi_penn file which includes GDP from IMF, Worldbank WDI and Penn world table 9.1.

It sounds like the missing values are beyond "the few." Given we are addressing the theta with multiple trials, we can do multiple imputations for the controls, too, if it is necessary. After all, we will end with a list of 100 datasets anyway.

> 3. Actually, now  cntrl_data_imp includes control variables for all 142 countries in our data between 1987 and 2019(1987 is included because we need lagged data).  Since we need to run the whole data with our theta from 1988 through 2019 finally , so I include all country_year variables instead of only variables in country_year which we have public opinion data.    But, I still save a version for country_year in our dcpo_input if it is needed.

I eagerly suggest the DCPO output (the `theta`s) to include the country and year information, for the sake of merging with controls in the later step.

**Comment by fsolt** [comment]
1. As the V-Dem variable is our DV, we can't really do anything for country-years that lack it. 
> Cassandra: For example, in our dcpo_input_yc, we have Slovakia 1990, 1992, however, Slovakia probably still belonged to Czech in 1990 and 1992 in Vdem.

I want to note that both Slovakia and Czechia were part of Czechoslovakia prior to the Velvet Divorce of 1993, so really _neither_ of them existed in 1990 or 1992.  It would be possible to put Czechoslovakia back together again, I suppose, in the 1990 and 1992 surveys, but it would be a drag.  There is V-Dem data for Czechoslovakia, I trust?

> Cassandra: One simple problem is Taiwan, which is in our data, but no population information from WB and Penn table. If we save it in our data, then we just need to fill up the population information.

Yep.  Missing control variables are different than the missing DV; we can multiply impute them if necessary.  Last I looked, the consensus was against imputing missing DVs.  Worth checking in on the state of the art there, I guess.

2.  > Hu: Given we are addressing the theta with multiple trials, we can do multiple imputations for the controls, too, if it is necessary. After all, we will end with a list of 100 datasets anyway.

Agreed.

3.  > Hu: I eagerly suggest the DCPO output (the thetas) to include the country and year information, for the sake of merging with controls in the later step.

Country and year are in the `dimnames` of the matrix `dcpo_theta` just as in `claassen_m5_theta`.  It's really the only place to put that info.  Did you write this before you got it figured out for `claassen_m5_theta`, or am I missing something?

**Comment by casstai** [comment]
En, there is no V-Dem data for Czechoslovakia. But, there is data for Czech Republic from 1918 to 2019. If there is no better way to deal with new countries,,  I guess I have to check them one by one.... still doable. 

> 1. As the V-Dem variable is our DV, we can't really do anything for country-years that lack it.
> 
> > Cassandra: For example, in our dcpo_input_yc, we have Slovakia 1990, 1992, however, Slovakia probably still belonged to Czech in 1990 and 1992 in Vdem.
> 
> I want to note that both Slovakia and Czechia were part of Czechoslovakia prior to the Velvet Divorce of 1993, so really _neither_ of them existed in 1990 or 1992. It would be possible to put Czechoslovakia back together again, I suppose, in the 1990 and 1992 surveys, but it would be a drag. There is V-Dem data for Czechoslovakia, I trust?
>

I could do multiple imputations for GDP per capita.
> 1. > Hu: Given we are addressing the theta with multiple trials, we can do multiple imputations for the controls, too, if it is necessary. After all, we will end with a list of 100 datasets anyway.
> 
> Agreed.

**Comment by sammo3182** [comment]
> Country and year are in the `dimnames` of the matrix dcpo_theta just as in claassen_m5_theta. It's really the only place to put that info. Did you write this before you got it figured out for claassen_m5_theta, or am I missing something?

I didn't see any dimnames in the `theta.rda`. 

```r
> dimnames(claassen_m5_theta$theta)
$iterations
NULL

[[2]]
NULL

[[3]]
NULL
```

That's the correct way to see the dimnames, right?

**Comment by sammo3182** [comment]
Cassandra @Tyhcass , a couple of clarification questions: 

1. The country names in `dcpo_input_update.rda` includes the following: "214". "76", "CÃ´te dâ€™Ivoire", and "SÃ£o TomÃ© & PrÃ­ncipe" ? Would they affect the mergence with the control data? 
1. Which GDP variable are we going to use? "lg_imp_imfgdp" or "lg_imp_mdpgdp"? They look identical in the summary.
1. Similarly, which  growth should we use, the mdp or imf?
1. Should we use dependenc_pc or dependenc_pc_di for the resource dependency?
1."muslism_prop_1990" or "muslism_prop_2010" ?

**Comment by casstai** [comment]
> Cassandra @Tyhcass , a couple of clarification questions:
> 
> 1. The country names in `dcpo_input_update.rda` includes the following: "214". "76", "CÃ´te dâ€™Ivoire", and "SÃ£o TomÃ© & PrÃ­ncipe" ? Would they affect the mergence with the control data?

Thanks, @sammo3182. I double-checked dcpo_input_raw.csv again. "214" "76"  are there.  "CÃ´te dâ€™Ivoire", and "SÃ£o TomÃ© & PrÃ­ncipe" can be solved by encoding ="UTF-8". However, as for "214" "74", it seems they are not the encoding problem. I tried latin1, but it is not useful.  I don't know why there are there.  Please stop using dcpo_input_update.  I created it by changing "Macedonia" to "North Macedonia" and format data to DCPO. However, it turns out dcpo_input_raw does not have identical country years in dcpo_inputc_cy.rda.. Then, when @fsolt feels better, we can check the problem. 

> 2. Which GDP variable are we going to use? "lg_imp_imfgdp" or "lg_imp_mdpgdp"? They look identical in the summary.

I see. You are right they are identical now. I  double-checked it. It turned out when I mutated log variables, I only logged mdpgdp....My fault..  I have corrected them and upload a new control_variables in data.  MDPgdppc is the data from MDP and imputed by imf, wb and penntable, while imfgdp is the data from IMF and imputed by wb, pentable and MDP. 

> 4. Should we use dependenc_pc or dependenc_pc_di for the resource dependency?
>    1."muslism_prop_1990" or "muslism_prop_2010" ?

We could use either one . Cls used 1990 one but the original link is missing in Pew. So, now muslism_prop_1990 is created by me following Cls's approach.  Muslism_prop_2010 is from Pew.  So, we could either one. 

For your Q3,  we will use  dependenc_pc_di which is a binary variable capturing whether the resource gdp pc is more than $1000. 
Again, thanks, @sammo3182.

**Comment by sammo3182** [comment]
Thanks for the clarification, Cassandra @Tyhcass . Just one quick point, though,

> "CÃ´te dâ€™Ivoire", and "SÃ£o TomÃ© & PrÃ­ncipe" can be solved by encoding ="UTF-8". 

I don't think that's the case. The default encoding of my machine is UTF-8, and it doesn't change anything.

**Comment by casstai** [comment]
> Thanks for the clarification, Cassandra @Tyhcass . Just one quick point, though,
> 
> > "CÃ´te dâ€™Ivoire", and "SÃ£o TomÃ© & PrÃ­ncipe" can be solved by encoding ="UTF-8".
> 
> I don't think that's the case. The default encoding of my machine is UTF-8, and it doesn't change anything.

En, interesting,,, it works at my end....

**Comment by sammo3182** [comment]
What are they anyway? Is there a possibility to just use the Latin letters?

**Comment by casstai** [comment]
@sammo3182 They are São Tomé & Príncipe  and  Côte d’Ivoire. Did you try encoding = LATIN1?  It didn't work at my end but no harm to try at your end if you haven't.

**Comment by sammo3182** [comment]
Nope, I meant "Sao Tome & Principe" and "Cote d'Ivoire" instead. I did try to turn off any pre encoding, yet nothing works. Strange Win 10 in Chinese, I guess...

**Comment by fsolt** [comment]
I solved the encoding issue, I think, (maybe it's introduced by GitHub? doesn't matter) here at https://github.com/fsolt/dcpo_dem_mood/commit/e1853c447862dafc05d9249cd4bcc829ecd80514#diff-3000070c7a5cbad2b4e63dee4cf2d78fR229.

**Comment by fsolt** [comment]
Here's what I see: of the countries we have thetas for, the control_variables file is missing data for Andorra, Belize, Myanmar (Burma), and Tajikistan.   V-Dem doesn't cover the first two, but it does the last two.  Can you please be sure they are included, Cassandra?

**Comment by casstai** [comment]
> Here's what I see: of the countries we have thetas for, the control_variables file is missing data for Andorra, Belize, Myanmar (Burma), and Tajikistan. V-Dem doesn't cover the first two, but it does the last two. Can you please be sure they are included, Cassandra?

I see.  I will double-check them..

**Comment by casstai** [comment]
> Here's what I see: of the countries we have thetas for, the control_variables file is missing data for Andorra, Belize, Myanmar (Burma), and Tajikistan. V-Dem doesn't cover the first two, but it does the last two. Can you please be sure they are included, Cassandra?

Interesting,,, only Belize in dcpo_input_cy.rd.. There is no Andorra, Myanmar (Burma), and Tajikistan in our dcpo_input_cy @fsolt. But we do have them in dcpo_input_raw.

**Comment by fsolt** [comment]
Okay, so that means Myanmar (Burma) and Tajikistan came in with wvs7.  Can you please add them to the control_variables file?

**Comment by casstai** [comment]
working on it.

**Comment by casstai** [comment]
New control_variables is ready now.  1. Missed Myanma and Tajikistan came from both wvs7 and asianb(Myanma) and asiab(Tajikistan).  2. Thanks to these missing data, I corrected several wrong codes I made in calculating GDP-related variables. Hope now we could run the analysis. Fingers crossed.

**Comment by fsolt** [comment]
Thanks, yes, that did the trick.  Getting the Macedonia/North Macedonia issue straightened out has made for longer DCPO convergence times (44hrs at 3k iter), and that run got the "Tail Effective Samples Size (ESS) is too low" warning (R-hats and so on look good though), so out of an abundance of caution I just started 4k iter.  That one probably won't be ready for our meeting Tuesday morning 😬.  In the meantime, here are the results from the 3k iter run:

<img width="720" alt="Screen Shot 2020-08-01 at 8 35 20 PM" src="https://user-images.githubusercontent.com/6536645/89113428-961c9700-d436-11ea-91e1-a6ad812c289e.png">


0.0051 $\pm$ .14 is pretty darn close to zero.  We need to get the 4k data and do the other three models as well, of course, but it isn't looking like our evidence will recuperate this hypothesis.

**Comment by fsolt** [comment]
Update: 4k iter took less time to run (42hrs) than 3k.  Maybe just lucky/unlucky with Argon.  In any event, as expected, no real change:

<img width="719" alt="Screen Shot 2020-08-03 at 9 56 14 PM" src="https://user-images.githubusercontent.com/6536645/89248144-9fdc0100-d5d4-11ea-8849-36117d4d742c.png">

If anything, .0049 $\pm$ .14 is even closer to zero.
