### ISSUE TITLE
analysis: include std dev of opinion

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_dem_mood#8]
that's part of "superior measure", right?

- [x] @fsolt : add sigma file to GitHub
- [x] @sammo3182: add sigma to models

**Comment by fsolt** [comment]
Changes nothing, btw

<img width="779" alt="Screen Shot 2020-08-05 at 8 35 54 AM" src="https://user-images.githubusercontent.com/6536645/89419268-cbefa300-d6f6-11ea-80e4-7bafe739aeb0.png">

**Comment by sammo3182** [comment]
The current version of `dcpo_sigma` in 33b235fced4ef6561f94b29cc3ae38334a86ad71 is actually `dcpo_theta`. A correction will be appreciated, Fred @fsolt. 

Also, it's not surprising that sigma doesn't make much difference, right? Theta is estimated with the account of the polarization. In this case, adding sigma does not bring new information into the model that already has the theta. Is that correct? If so, should we still include it in the model?

**Comment by sammo3182** [comment]
To manifest the superior of accounting for the polarization, maybe we can just show how sigma is different along the time or across the countries?

**Comment by fsolt** [comment]
Blech.  Sorry about that.  Fixed in https://github.com/fsolt/dcpo_dem_mood/commit/e804bffe869cdef06565e4d4a674715965eea46e.

Showing some of the polarization values is a good idea if we have space.  I guess, if not, can still go into appendix.

**Comment by fsolt** [comment]
I'm not sure that it's not surprising that polarization doesn't make a difference.  Given the null result on theta, there was the possibility that the what really matters is not so much the level of opinion but that everyone agrees to it--I still think this is plausible for Models 2 and 4.  If not, then the argument in favor of the null is [this stuff](https://github.com/fsolt/dcpo_dem_mood/issues/10#issuecomment-669176256).  And you know I love laying out all the arguments.

**Comment by casstai** [comment]
Another question, in the model, the dataset includes 2020 data and countries with no V-dem values. Does it matter?  Should we drop them before running models?

**Comment by fsolt** [comment]
The observations with missing data get dropped automatically (rowwise deletion), so I don’t think we need to worry about them.  We’ve confirmed that all the obs that should be complete are complete.

**Comment by casstai** [comment]
I checked the missing values in dataset in the model. São Tomé & Príncipe and Côte d’Ivoire do not have control variables.  They failed to merge with control_variables.

**Comment by fsolt** [comment]
Where are you checking?  They seem fine in `df_dcpo` . . .
<img width="1014" alt="Screen Shot 2020-08-07 at 4 02 16 PM" src="https://user-images.githubusercontent.com/6536645/89688261-64d51880-d8c7-11ea-9b1b-047a58c787d7.png">
.

**Comment by casstai** [comment]
Er,, then, maybe my laptop problems....  I followed all codes. 
![Capture](https://user-images.githubusercontent.com/46602397/89688654-44f22480-d8c8-11ea-94c9-d3077382b3c8.JPG)

**Comment by fsolt** [comment]
Blech.  And `df_dcpo` is way too big to just save to the repo . . .

**Comment by sammo3182** [comment]
> Blech. Sorry about that. Fixed in [e804bff](https://github.com/fsolt/dcpo_dem_mood/commit/e804bffe869cdef06565e4d4a674715965eea46e).
> 
> Showing some of the polarization values is a good idea if we have space. I guess, if not, can still go into appendix.

Look at this (also the codes in ad92403b644ce314f56fbd4f64821ef7ddb76652):
![image](https://user-images.githubusercontent.com/6463211/89706244-67eb0a00-d996-11ea-8d86-391641107cf2.png)

(There are error bars in the right plot, but you can't see them because they are too small in comparison with the x scale.) The difference in polarization looks dramatically salient. Please help me to check if the results make sense or there's any mistake in the codes , my fellows @fsolt @Tyhcass. If they look ok, I suggest us to show them in the paper---if not the PA paper, Fred!---to show the importance of addressing polarization and what Claassen et al. has neglected! We definitely need a subsample of the countries, though, if you also agree to include the plot.

https://github.com/fsolt/dcpo_dem_mood/blob/ad92403b644ce314f56fbd4f64821ef7ddb76652/paper/dcpo_demsupport.Rmd#L408-L477

**Comment by sammo3182** [comment]
> I'm not sure that it's not surprising that polarization doesn't make a difference. Given the null result on theta, there was the possibility that the what really matters is not so much the level of opinion but that everyone agrees to it--I still think this is plausible for Models 2 and 4. If not, then the argument in favor of the null is [this stuff](https://github.com/fsolt/dcpo_dem_mood/issues/10#issuecomment-669176256). And you know I love laying out all the arguments.

I didn't mean it's not surprising that polarization doesn't make a difference, Fred. I was not surprised it's statistically insignificant in our model because the thetas have included the information of polarization when they were estimated through DCPO. It's just like if you already rule out the country differences as a whole through fixed effects, you probably won't see anything in, e.g., the variable about the economic difference among the countries. 

Based on this point, I would argue that the null result of polarization is not because it doesn't change anything (see the above plots---how much difference they have led!), but its effect has been "over-controlled."

**Comment by casstai** [comment]
First, let me go off the point a little bit. I do like the code writing of both of you  @fsolt @sammo3182 . Admire your code writing! I am still making mistakes in using Github features.....Sigh. ...Now, let's get back to the point. 
I'm a big fun of DCPO's polarization feature! I think the two graphs are so cool~~ Btw, why the U.S. democracy polarization is so wavy? What is the theta shape?  It seems the polarization was on the crest or on the way to crest when GOP presidents were elected (1988,2000,2004, and 2016). Interesting, right? Maybe polarization is not related to the democratic level but also which party will win or vice versa.........  What I am thinking is,  since now we have the null result, we may need to modify the models or have a good argument for the polarization variable if we take the polarization as a selling point. Graphs might not be enough to show the importance of DCPO's polarization feature. Although theta is from sigma, regardless of models, what are the correlations between theta and V-dem (Both Claassen and Caughey used it in their method papers) and between sigma and V-dem?   I do believe sigma could tell a good story, and we just need to find a way to show it, like subgrouping them.
